-- MySQL Script generated by MySQL Workbench
-- Tue Dec  3 16:22:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jimmyJimmy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jimmyJimmy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jimmyJimmy` ;
USE `jimmyJimmy` ;

-- -----------------------------------------------------
-- Table `jimmyJimmy`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jimmyJimmy`.`genero` (
  `idgenero` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jimmyJimmy`.`jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jimmyJimmy`.`jogo` (
  `idjogo` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `desenvolvedora` VARCHAR(45) NOT NULL,
  `data_lancamento` VARCHAR(45) NOT NULL,
  `idiomas` VARCHAR(45) NOT NULL,
  `midia` VARCHAR(45) NOT NULL,
  `genero_idgenero` INT NOT NULL,
  PRIMARY KEY (`idjogo`),
  INDEX `fk_jogo_genero1_idx` (`genero_idgenero` ASC),
  CONSTRAINT `fk_jogo_genero1`
    FOREIGN KEY (`genero_idgenero`)
    REFERENCES `jimmyJimmy`.`genero` (`idgenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jimmyJimmy`.`fase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jimmyJimmy`.`fase` (
  `idfase` INT NOT NULL AUTO_INCREMENT,
  `pontos` INT NULL DEFAULT NULL,
  `nome` VARCHAR(30) NULL DEFAULT NULL,
  `dirPersonagem` VARCHAR(50) NULL DEFAULT NULL,
  `dirColecionavel` VARCHAR(50) NULL DEFAULT NULL,
  `dirCenario` VARCHAR(50) NULL DEFAULT NULL,
  `dirChao` VARCHAR(50) NULL DEFAULT NULL,
  `jogo_idjogo` INT NOT NULL,
  PRIMARY KEY (`idfase`),
  INDEX `fk_fase_jogo1_idx` (`jogo_idjogo` ASC),
  CONSTRAINT `fk_fase_jogo1`
    FOREIGN KEY (`jogo_idjogo`)
    REFERENCES `jimmyJimmy`.`jogo` (`idjogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `jimmyJimmy`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jimmyJimmy`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nick` VARCHAR(30) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nome_fase` VARCHAR(30) NULL DEFAULT NULL,
  `max_ptos` INT NULL DEFAULT NULL,
  `idFase` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_idFase` (`idFase` ASC),
  CONSTRAINT `fk_idFase`
    FOREIGN KEY (`idFase`)
    REFERENCES `jimmyJimmy`.`fase` (`idfase`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jimmyJimmy`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jimmyJimmy`.`comentario` (
  `idcomentario` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `data` DATETIME(6) NOT NULL,
  `estrelas` INT NULL DEFAULT NULL,
  `jogo_idjogo` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idcomentario`),
  INDEX `fk_comentario_jogo1_idx` (`jogo_idjogo` ASC),
  INDEX `fk_comentario_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_comentario_jogo1`
    FOREIGN KEY (`jogo_idjogo`)
    REFERENCES `jimmyJimmy`.`jogo` (`idjogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `jimmyJimmy`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
